name: smart_pharma_net
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  build_runner: ^2.4.7
  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^8.0.3
  http: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  shared_preferences: ^2.2.1
  flutter_lints: ^2.0.0
  jwt_decoder: ^2.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/welcome_img_screen.png
    - assets/icons/google.png
    - assets/icons/facebook-logo-in-circular-shape.png
    - assets/icons/apple-black-logo.png
    - assets/icons/menu-bar.png
    - assets/icons/search_icon.png
    - assets/icons/person.png
    - assets/icons/app_icon.png